<?php


declare( strict_types = 1 );


use JDWX\Options\AbstractOptionSet;
use JDWX\Options\OptionableInterface;
use JDWX\Options\OptionInterface;


readonly class MyOptionSet extends AbstractOptionSet {


    public static function interface( ?string $i_nstOptionInterface = null ) : string {
        static $stOptionInterface = OptionInterface::class;
        if ( ! is_null( $i_nstOptionInterface ) ) {
            $stOptionInterface = $i_nstOptionInterface;
        }
        return $stOptionInterface;
    }


    public static function set( OptionableInterface|array|OptionInterface|null ...$rOptions ) : static {
        return new static( static::interface(), $rOptions );
    }


    public function fetchBooleanPub( string $i_stClass ) : bool {
        return parent::fetchBoolean( $i_stClass );
    }


    public function fetchIntPub( string $i_stClass ) : ?int {
        return parent::fetchInt( $i_stClass );
    }


    public function fetchListPub( string $i_stClass ) : ?array {
        return parent::fetchList( $i_stClass );
    }


    public function fetchStringPub( string $i_stClass ) : ?string {
        return parent::fetchString( $i_stClass ); // TODO: Change the autogenerated stub
    }


    public function fetchValuePub( string $i_stClass ) : mixed {
        return parent::fetchValue( $i_stClass );
    }


}
